### ISSUE TITLE
"Search by user Name" crashes and doesn't work.

### ISSUE THREAD

**Issue by AshishKapoor** [jamesrochabrun/TwitterFabric#2]
**Steps to reproduce:**
1. Log in using your Twitter profile.
2. Click on "Search by user Name"
3. Write anything on the pop-up and press "Search"
4. 
- Case 4.1: Enter string with spaces makes it crash 
- Case 4.2: Enter string without spaces with any username you know that exists on Twitter. It shows the current user itself.

**Comment by jamesrochabrun** [comment]
case 4.1 when a search is implemented with spaces the endpoint gets corrupted, I change the logic to eliminate spaces and now the endpoint can handle that situation.
case 4.2 looks like the endpoint don't return a specific user it returns a list of users that its names or username contains the query provided by the search. the solution will be looking inside Twitter documentation a different endpoint that handles that request.
